# =====================================================================
# TV AZTECA DIGITAL - SNOWFLAKE CONFIGURATION
# =====================================================================
# Configuración de conexión a Snowflake
# Reemplaza los valores con tus credenciales reales

[snowflake]
account = "your_account_identifier"  # Ej: "xy12345.us-east-1"
user = "your_username"               # Tu usuario de Snowflake
password = "your_password"           # Tu contraseña
warehouse = "TVAZTECA_WH"           # Warehouse creado en el demo
database = "TVAZTECA_DB"            # Base de datos del demo
schema = "RAW_SCHEMA"               # Schema principal
role = "TVAZTECA_ANALYST_ROLE"      # Rol creado en el demo

# Configuración adicional
[app]
environment = "demo"                 # Entorno de la aplicación
debug = true                        # Modo debug habilitado

# Configuración de cache
[cache]
ttl = 600                          # Cache TTL en segundos (10 minutos)
max_entries = 1000                 # Máximo número de entradas en cache


