-- =================================================================
-- MONEX GRUPO FINANCIERO - SNOWFLAKE CORTEX SETUP
-- Sistema completo con Cortex Analyst y Cortex Search
-- =================================================================

-- Configuración inicial
USE ROLE ACCOUNTADMIN;

-- Crear warehouse para el proyecto
CREATE OR REPLACE WAREHOUSE MONEX_WH WITH
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    COMMENT = 'Warehouse para aplicaciones Monex Cortex';

-- Crear base de datos principal
CREATE OR REPLACE DATABASE MONEX_DB
    COMMENT = 'Base de datos principal para Monex Grupo Financiero';

-- Crear esquemas
CREATE OR REPLACE SCHEMA MONEX_DB.CORE
    COMMENT = 'Esquema principal con datos operativos';

CREATE OR REPLACE SCHEMA MONEX_DB.ANALYTICS
    COMMENT = 'Esquema para vistas analíticas y métricas';

CREATE OR REPLACE SCHEMA MONEX_DB.DOCUMENTS
    COMMENT = 'Esquema para documentos y servicios de búsqueda';

CREATE OR REPLACE SCHEMA MONEX_DB.STAGES
    COMMENT = 'Esquema para stages y archivos';

-- Usar la base de datos
USE DATABASE MONEX_DB;
USE SCHEMA CORE;
USE WAREHOUSE MONEX_WH;

-- =================================================================
-- CREAR TABLAS PRINCIPALES
-- =================================================================

-- Tabla de Clientes
CREATE OR REPLACE TABLE CLIENTES (
    CLIENTE_ID VARCHAR(20) PRIMARY KEY,
    NOMBRE VARCHAR(200) NOT NULL,
    TIPO_CLIENTE VARCHAR(20) NOT NULL, -- 'CORPORATIVO', 'PRIVADO', 'INDIVIDUAL'
    RFC VARCHAR(13),
    TELEFONO VARCHAR(15),
    EMAIL VARCHAR(100),
    CIUDAD VARCHAR(50),
    ESTADO VARCHAR(50),
    PAIS VARCHAR(50) DEFAULT 'MÉXICO',
    FECHA_ALTA DATE NOT NULL,
    ESTATUS VARCHAR(20) DEFAULT 'ACTIVO',
    SEGMENTO VARCHAR(30), -- 'EMPRESARIAL', 'PYME', 'PREMIUM', 'MASIVO'
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Tabla de Productos Financieros
CREATE OR REPLACE TABLE PRODUCTOS (
    PRODUCTO_ID VARCHAR(20) PRIMARY KEY,
    NOMBRE_PRODUCTO VARCHAR(100) NOT NULL,
    CATEGORIA VARCHAR(50) NOT NULL, -- 'CREDITO', 'INVERSION', 'CAMBIO_DIVISAS', 'FACTORAJE', 'CUENTA'
    SUBCATEGORIA VARCHAR(50),
    MONEDA VARCHAR(3) DEFAULT 'MXN',
    TASA_INTERES DECIMAL(8,4),
    COMISION DECIMAL(8,4),
    MONTO_MINIMO DECIMAL(15,2),
    MONTO_MAXIMO DECIMAL(15,2),
    DESCRIPCION VARCHAR(500),
    ESTATUS VARCHAR(20) DEFAULT 'ACTIVO',
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Tabla de Transacciones
CREATE OR REPLACE TABLE TRANSACCIONES (
    TRANSACCION_ID VARCHAR(30) PRIMARY KEY,
    CLIENTE_ID VARCHAR(20) NOT NULL,
    PRODUCTO_ID VARCHAR(20) NOT NULL,
    TIPO_TRANSACCION VARCHAR(30) NOT NULL, -- 'DEPOSITO', 'RETIRO', 'TRANSFERENCIA', 'INVERSION', 'CAMBIO_FX'
    MONTO DECIMAL(15,2) NOT NULL,
    MONEDA VARCHAR(3) NOT NULL,
    FECHA_TRANSACCION TIMESTAMP NOT NULL,
    ESTADO VARCHAR(20) DEFAULT 'COMPLETADA',
    CANAL VARCHAR(20), -- 'SUCURSAL', 'DIGITAL', 'TELEFONO', 'ATM'
    SUCURSAL VARCHAR(50),
    DESCRIPCION VARCHAR(200),
    COMISION DECIMAL(10,2) DEFAULT 0,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID),
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(PRODUCTO_ID)
);

-- Tabla de Inversiones y Fondos
CREATE OR REPLACE TABLE INVERSIONES (
    INVERSION_ID VARCHAR(30) PRIMARY KEY,
    CLIENTE_ID VARCHAR(20) NOT NULL,
    FONDO_ESTRATEGIA VARCHAR(50) NOT NULL, -- 'USD_FIXED_INCOME', 'GLOBAL_EQUITY', 'CONSERVATIVE', 'MODERATE', 'AGGRESSIVE'
    MONTO_INVERTIDO DECIMAL(15,2) NOT NULL,
    MONEDA VARCHAR(3) NOT NULL,
    FECHA_INVERSION DATE NOT NULL,
    FECHA_VENCIMIENTO DATE,
    RENDIMIENTO_ANUAL DECIMAL(8,4),
    VALOR_ACTUAL DECIMAL(15,2),
    ESTADO VARCHAR(20) DEFAULT 'ACTIVA',
    NOTAS VARCHAR(300),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID)
);

-- Tabla de Tipos de Cambio
CREATE OR REPLACE TABLE TIPOS_CAMBIO (
    FECHA DATE NOT NULL,
    MONEDA_ORIGEN VARCHAR(3) NOT NULL,
    MONEDA_DESTINO VARCHAR(3) NOT NULL,
    TIPO_CAMBIO_COMPRA DECIMAL(10,6) NOT NULL,
    TIPO_CAMBIO_VENTA DECIMAL(10,6) NOT NULL,
    VOLUMEN_TRANSACCIONES DECIMAL(15,2) DEFAULT 0,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    
    PRIMARY KEY (FECHA, MONEDA_ORIGEN, MONEDA_DESTINO)
);

-- Tabla de Factoraje
CREATE OR REPLACE TABLE FACTORAJE (
    FACTORAJE_ID VARCHAR(30) PRIMARY KEY,
    CLIENTE_ID VARCHAR(20) NOT NULL,
    NUMERO_FACTURA VARCHAR(50) NOT NULL,
    EMPRESA_DEUDORA VARCHAR(200) NOT NULL,
    MONTO_FACTURA DECIMAL(15,2) NOT NULL,
    MONTO_ADELANTO DECIMAL(15,2) NOT NULL,
    FECHA_FACTURA DATE NOT NULL,
    FECHA_VENCIMIENTO DATE NOT NULL,
    FECHA_OPERACION DATE NOT NULL,
    TASA_DESCUENTO DECIMAL(8,4) NOT NULL,
    COMISION DECIMAL(8,4) NOT NULL,
    ESTADO VARCHAR(20) DEFAULT 'VIGENTE', -- 'VIGENTE', 'COBRADO', 'VENCIDO'
    TIPO_FACTORAJE VARCHAR(20) DEFAULT 'SIN_RECURSO', -- 'CON_RECURSO', 'SIN_RECURSO'
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID)
);

-- Tabla de Documentos (para Cortex Search)
CREATE OR REPLACE TABLE DOCUMENTOS (
    DOCUMENTO_ID VARCHAR(30) PRIMARY KEY,
    CLIENTE_ID VARCHAR(20),
    TITULO VARCHAR(200) NOT NULL,
    TIPO_DOCUMENTO VARCHAR(50) NOT NULL, -- 'CONTRATO', 'MANUAL', 'POLITICA', 'REPORTE', 'COMUNICADO'
    CATEGORIA VARCHAR(50), -- 'CREDITO', 'INVERSION', 'FACTORAJE', 'NORMATIVO', 'OPERATIVO'
    CONTENIDO TEXT NOT NULL,
    FECHA_DOCUMENTO DATE NOT NULL,
    ESTADO VARCHAR(20) DEFAULT 'ACTIVO',
    IDIOMA VARCHAR(10) DEFAULT 'ES',
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID)
);

-- =================================================================
-- HABILITAR CHANGE TRACKING PARA CORTEX SEARCH
-- =================================================================

ALTER TABLE DOCUMENTOS SET CHANGE_TRACKING = TRUE;

-- =================================================================
-- CREAR VISTAS ANALÍTICAS
-- =================================================================

CREATE OR REPLACE VIEW ANALYTICS.RESUMEN_CLIENTES AS
SELECT 
    TIPO_CLIENTE,
    SEGMENTO,
    ESTADO,
    COUNT(*) AS TOTAL_CLIENTES,
    COUNT(CASE WHEN ESTATUS = 'ACTIVO' THEN 1 END) AS CLIENTES_ACTIVOS,
    MIN(FECHA_ALTA) AS PRIMERA_FECHA_ALTA,
    MAX(FECHA_ALTA) AS ULTIMA_FECHA_ALTA
FROM CORE.CLIENTES
GROUP BY TIPO_CLIENTE, SEGMENTO, ESTADO;

CREATE OR REPLACE VIEW ANALYTICS.METRICAS_TRANSACCIONES AS
SELECT 
    DATE_TRUNC('MONTH', FECHA_TRANSACCION) AS MES,
    TIPO_TRANSACCION,
    MONEDA,
    COUNT(*) AS NUMERO_TRANSACCIONES,
    SUM(MONTO) AS VOLUMEN_TOTAL,
    AVG(MONTO) AS MONTO_PROMEDIO,
    SUM(COMISION) AS COMISIONES_TOTALES
FROM CORE.TRANSACCIONES
WHERE ESTADO = 'COMPLETADA'
GROUP BY DATE_TRUNC('MONTH', FECHA_TRANSACCION), TIPO_TRANSACCION, MONEDA;

CREATE OR REPLACE VIEW ANALYTICS.RENDIMIENTO_INVERSIONES AS
SELECT 
    FONDO_ESTRATEGIA,
    MONEDA,
    COUNT(*) AS NUMERO_INVERSIONES,
    SUM(MONTO_INVERTIDO) AS CAPITAL_TOTAL,
    SUM(VALOR_ACTUAL) AS VALOR_ACTUAL_TOTAL,
    AVG(RENDIMIENTO_ANUAL) AS RENDIMIENTO_PROMEDIO,
    (SUM(VALOR_ACTUAL) - SUM(MONTO_INVERTIDO)) AS GANANCIA_PERDIDA_TOTAL
FROM CORE.INVERSIONES
WHERE ESTADO = 'ACTIVA'
GROUP BY FONDO_ESTRATEGIA, MONEDA;

-- =================================================================
-- CREAR STAGES PARA ARCHIVOS
-- =================================================================

CREATE OR REPLACE STAGE STAGES.SEMANTIC_MODELS
    COMMENT = 'Stage para modelos semánticos YAML';

CREATE OR REPLACE STAGE STAGES.STREAMLIT_APP
    COMMENT = 'Stage para aplicación Streamlit';

-- =================================================================
-- CONFIGURAR PERMISOS
-- =================================================================

-- Crear rol específico para la aplicación
CREATE OR REPLACE ROLE MONEX_APP_ROLE;

-- Otorgar permisos al rol
GRANT USAGE ON DATABASE MONEX_DB TO ROLE MONEX_APP_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE MONEX_DB TO ROLE MONEX_APP_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA CORE TO ROLE MONEX_APP_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA ANALYTICS TO ROLE MONEX_APP_ROLE;
GRANT USAGE ON WAREHOUSE MONEX_WH TO ROLE MONEX_APP_ROLE;

-- Otorgar rol Cortex User
GRANT ROLE SNOWFLAKE.CORTEX_USER TO ROLE MONEX_APP_ROLE;

-- Permisos para stages
GRANT READ, WRITE ON STAGE STAGES.SEMANTIC_MODELS TO ROLE MONEX_APP_ROLE;
GRANT READ, WRITE ON STAGE STAGES.STREAMLIT_APP TO ROLE MONEX_APP_ROLE;

-- Otorgar el rol al usuario actual
GRANT ROLE MONEX_APP_ROLE TO USER CURRENT_USER();

COMMIT;

SELECT 'Setup de base de datos completado exitosamente!' AS STATUS;


